### ISSUE TITLE
Is anyone actually working on this?

### ISSUE THREAD

**Issue by MrUzagi** [sylvanaar/prat-3-0#200]
All I ever see lately are issues getting auto-tagged as stale after a couple of months, and then closed a week later. 

I imagine this, too, will get tagged as stale, and then closed. If/when it is it will be a signal to me it's time to move on.

**Comment by sylvanaar** [comment]
I have been working on the project for  IDK how many years anymore. Something like 13 years. Invariably, there are times when I work on it more or less. I worked on it quite a bit before the expansion last year. It got a significant overhaul, new implementations of many things, and I would say a few substantial new features.

This year has been tough on me work-wise, so I haven't spent as much time on it - but was lucky to have some contributions from the community which I really appreciate. Quite honestly in all those years, I haven't gotten as many as I have this past year, and I am very grateful.

You have a point - from your perspective it may seem to be worked on much less.  From mine- it has had more work on it this past 12 months than many of the past few years. Very difficult to say really.

So - these days, my workdays are 14-16 hours - since July maybe. I do still find time for side projects too even then.

The bot does help - you know sometimes people leave tickets - and are impossible to find after that - to stop the bot from closing stuff you just say "hi I'm still here" I think right? That is how I thought It worked - I set the bot with timeframes that made sense  whenI was very active on last year - perhaps I should make them longer though.

Thanks.

**Comment by MrUzagi** [comment]
Thank you for a nice explanation (and add-on I might add).

I do understand the job of the bot. Seeing issues lingering untouched for years is not ideal either. Neither for developer nor user.
It seems the time will be extended with activity in the thread. I did that earlier last year with an issue that was marked as stale, and it took another couple of months before it was marked as stale again. After which I gave up.

However. I think many people will ask a question or make an issue, and if there's no replies in a couple of months they probably will, as I have, assume no one is interested in fixing or answering and won't pursue the issue. Then you learn to live with the issue, find a fix elsewhere or find another addon.

That said, I'm still hanging on to the addon. I've used it for years and there are simply too many QoL I use to stop now. And your reply made me extend the time until I consider the addon stale. :-D

**Comment by StragaSevera** [comment]
> The bot does help - you know sometimes people leave tickets - and are impossible to find after that

Hmm, if you see a bot closing a ticket without any response, and seeing that this same bot closed a lot of other tickets without any response, it paints a picture that there is no reason to open them. If, on the other hand, there is some manual intervention - like a question: "Is this issue stil valid, do you have this problem still?" - then you see that there is a reason to open issues =-)

Thank you for your time and free work on this heavy addon, by the way ;-)

**Comment by DiscordGregory** [comment]
I miss you in Discord Sylvanaar! 👯‍♂️

**Comment by addonaddict** [comment]
I understand real life comes first but if tickets are left open for months and months for something that can be fixed/added in about 5-15m of work then it is all just neglect / non-interest in the game
If you could hand over the project to someone or just add someone to assist you that would be great
Chat addons are some of the easiest to code sorry to say, hope everything works out for you IRL but it's just no excuse
It just sucks that there are no real alternatives to this addon in terms of QoL features... too bad

**Comment by gizzmo** [comment]
> Chat addons are some of the easiest to code

If they're so easy, make some pull requests. That's what's great about open source projects. Anyone can contribute.

**Comment by addonaddict** [comment]
> > Chat addons are some of the easiest to code
> 
> If they're so easy, make some pull requests. That's what's great about open source projects. Anyone can contribute.

If I knew how to code I wouldnt be wasting creating numeroues issues just to see them get auto-deleted by inactive developer that seems to have lost all interest / quit

Instead of kissing ass with your obvious sarcasm why not do something productive with your time instead

**Comment by StragaSevera** [comment]
> If I knew how to code

If you don't know how to code, why do you think you know what is easy and what is hard?

I mean, the current neglect situation is very sad, but it does not mean that the job is easy.

**Comment by addonaddict** [comment]
I know enough to code something basic when it comes to chat
Its easy as hell compared to anything else out there
We gonna keep up the conversation or you just about done kissing ass?

**Comment by StragaSevera** [comment]
Something basic, yes. The mod with so many modules, no.

And you are free to stop this conversation whenever you want, having such a big fixation on somebody's ass is unhealthy for you ;-)

**Comment by addonaddict** [comment]
Oh yea because adding another module that changes font colour is so difficult
Come on now, your breath stinks from kissing all that ass

**Comment by StragaSevera** [comment]
Sorry, but I'll leave your erotic roleplay to you. Good luck with getting your senpai to notice you ;-)

**Comment by addonaddict** [comment]
Too bad it'll be lonely
I'll give it a few years before i give up

**Comment by MrUzagi** [comment]
@StragaSevera Don't feed the troll. It serves no purpose.
@addonaddict Way to derail the discussion. Personal attacks surely will progress the development. Obvious troll is obvious.

**Comment by addonaddict** [comment]
WaWaWa - i discussed the fact that the addon is abandoned and im the troll that is being fed. LMAO
Smells like ass juice in here
