### ISSUE TITLE
Window size and position not saving

### ISSUE THREAD

**Issue by Smexhy** [sylvanaar/prat-3-0#234]
Hey, for some reason, chat window position is not saving and after I exit the game or log out few times, it reverts back to being a slightly off at positioning for some reason. Any idea how to force prat to save the chat window position instead of using blizz's config which is changing it all the time?

I am on the latest addon version on Wotlk classic

**Comment by Devinmarra** [comment]
Hello! Thank you for using Prat! Sadly this repo is no longer maintained as Sylvanaar passed away. We've forked his project in a new repo, and thanks to some brilliant developers in the community, we are keeping his project going in his honor. Please open your issue here if you're still having trouble.

https://github.com/Legacy-of-Sylvanaar/prat-3-0/issues

**Comment by Smexhy** [comment]
Oh I am sorry, thank you for letting me know, I will.
